crowd:
  hostname: crowd
  build: docker/crowd
  ports:
    - "8095:8095" # no cache
  links:
    - database
  volumes:
    - home:/opt/crowd-home
  restart: always

database:
  hostname: database
  build: docker/postgres
  volumes:
    - tmp:/tmp # import backups
    - data:/var/lib/postgresql/data
  restart: always
